modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/TeamGalacticraft/DynamicDimensions/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://galacticraft.dev/"
logoFile="${mod_id}.png"
credits="Team Galacticraft"
authors="Team Galacticraft"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
