modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL="https://github.com/TeamGalacticraft/DynamicDimensions/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://galacticraft.dev/"
logoFile="${mod_id}.png"
credits="Team Galacticraft"
authors="Team Galacticraft"
description='''
${mod_description}
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "badpackets"
type="required"
versionRange = "[0.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"
